eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL of the Eureka Server
    registerWithEureka: true  # Register this service with Eureka
    fetchRegistry: true  # Fetch registry info from Eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"
              allow-credentials: true
      routes:
        - id: shortner
          uri: lb://shortner
          filters:
            - RewritePath=/s/(?<segment>.*), /$\{segment}
          predicates:
            - Path=/s/**
server:
  port: 8001
